# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

env:
  - KERAS_BACKEND="tensorflow"

apt_packages:
  - libudunits2-dev

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis virtualenv
  - pip2.7 install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano tensorflow

